### PR TITLE
Sane defaults for CLI flags

### PR DESCRIPTION
**Pull request by jstavh**
Adding sane defaults for CLI flags.

### CODE REVIEW

**Comment by jenr24G** [comment]
maybe we could put these directories in a `mina-indexer` folder in the user's home directory, and just name them as they are called in the `ServerArgs`. You would have to create the `mina-indexer` folder in the startup function if the defaults are used, though!

**Comment by jstavh** [comment]
> maybe we could put these directories in a `mina-indexer` folder in the user's home directory, and just name them as they are called in the `ServerArgs`. You would have to create the `mina-indexer` folder in the startup function if the defaults are used, though!

@jenr24G I implemented your idea 😄

**Comment by jstavh** [comment]
Wait, I need to add one more sane default to root_hash

**Comment by jenr24G** [comment]
Last comment: i'd reccomend removing `default` from the names, also, make sure you run `cargo fmt` and `cargo clippy`!

**Review by jenr24G — APPROVED** [review]
LGTM!

**Pull request merged**
