### PR TITLE
Fix issue 673

### PR DESCRIPTION
**Pull request by robinbb**
Fixes: https://github.com/Granola-Team/mina-indexer/issues/673

### CODE REVIEW

**Comment by jhult** [comment]
@robinbb, your commit for #679 snuck into this.

**Comment by robinbb** [comment]
@jhult I don't think it did? Double check. Or, clarify?

**Comment by jhult** [comment]
https://github.com/Granola-Team/mina-indexer/pull/682/commits

image

**Review by jhult — APPROVED** [review]
LGTM

**Pull request merged**
