### PR TITLE
Fix #229 - Add regression suite to the CI pipeline

### LINKED ISSUE #229: Problem: Regression test suite not automatically run in CI/CD pipeline on PRs
Add the regression test suite to the github actions workflow

### PR DESCRIPTION
**Pull request by trevorbernard**

### CODE REVIEW

**Comment by trevorbernard** [comment]
This PR is dependant on the following PR being merged into `main` https://github.com/Granola-Team/mina-indexer/pull/228. Marking as Draft until it gets merged

**Review by jenr24G — APPROVED** [review]

**Review by jenr24G — CHANGES_REQUESTED** [review]
looks like ci is trying to create a `/blocks` dir in the root, maybe change this to `./blocks`

**Comment by trevorbernard** [comment]
> looks like ci is trying to create a `/blocks` dir in the root, maybe change this to `./blocks`

The problem is that TMP environment variable isn't being set and causing it to evaluate to `/blocks`. I fixed this issue in the PR #288. Once that's merged I'll rebase and it should be resolved

**Comment by trevorbernard** [comment]
Better way in another PR. Closing

**Pull request closed without merging**
