### PR TITLE
Use just in the CI/CD pipeline

### PR DESCRIPTION
**Pull request by trevorbernard**
Fix https://github.com/Granola-Team/mina-indexer/issues/229 - Use Just in the CI/CD Pipeline to trigger the regression suite

### CODE REVIEW

**Review by robinbb — APPROVED** [review]

**Comment by robinbb** [comment]
Test doesn't actually pass ATM, it appears.

**Comment by Isaac-DeFrain** [comment]
I think you meant `just`, not `jest`. Changing PR name.

**Comment by trevorbernard** [comment]
> I think you meant `just`, not `jest`. Changing PR name.

Indeed

**Review by Isaac-DeFrain — APPROVED** [review]
LGTM

**Pull request merged**
