### PR TITLE
Always just deploy main to production if testing passes

### PR DESCRIPTION
**Pull request by robinbb**
What I did to test this:
1. I ran the ops/productionize script on my own machine. Works.
2. I ran the ops/productionize script manually on the 'nixos-builder-1' machine, which is the production machine, as of now. It works.
3. I checked api.minasearch.com/graphql to make sure that the GraphIQL page is returned. Works.

### CODE REVIEW

**Comment by robinbb** [comment]
#yolo

**Review by jhult — APPROVED** [review]
Woohoo!

**Comment by robinbb** [comment]
I also redeployed the nixos-builder-1 to make sure that the infra scripts match the config that Jonathan applied manually, and I made sure that the 'production=true' Buildkite tag was correctly applied to the agents on that machine.

**Comment by robinbb** [comment]
... and I deleted the special handling for the 'prod' branch in GitHub settings.

**Pull request merged**
