### PR TITLE
Fix nix build issues on aarch64-darwin

### PR DESCRIPTION
**Pull request by trevorbernard**
* Fixes: https://github.com/Granola-Team/mina-indexer/issues/481

### CODE REVIEW

**Comment by trevorbernard** [comment]
@robinbb can you see if this fix also fixes your `x86_64-darwin` woes as well?

**Comment by jhult** [comment]
This appears to fix it for me on an Apple M1.

**Comment by trevorbernard** [comment]
> This changes nothing for me on MacOS/Intel, but it's obviously still net positive.

My workflow depends on the nix working. It was slowing me down

**Comment by robinbb** [comment]
Well worth doing this fix!

**Pull request merged**
