### PR TITLE
Process transfers as debit/credit pairs in `InternalCommand::from_precomputed` function 

### PR DESCRIPTION
**Pull request by n1tranquilla**
## Describe your changes
* The main algorithm is now `O(n)` instead of `O(n * log(n))` 
* It is easier to read as transfers are now processed in debit/credit pairs
* For balanced pairs, runtime asserts that debits and credits sum to zero
* A duplicate was found in the feetransfers GQL for the first 120 blocks. This was fixed as a result of the rewrite.

## Link issue(s) fixed
Closes: #1352

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have verified new and existing tests pass locally with my changes.
- [x] I verified whether it was necessary to increment the database version.

### CODE REVIEW

**Comment by n1tranquilla** [comment]
A comparison between the production and local instances on the feetransfers endpoint reveals that there is one duplicate entry in the production version, which is not present in mine. 

Screen Shot 2024-08-14 at 8 55 09 AM

This means I should update the feetransfers.hurl test

**Review by Isaac-DeFrain — COMMENTED** [review]
Nice work!

**Comment by robinbb** [comment]
> A comparison between the production and local instances on the feetransfers endpoint reveals that there is one duplicate entry in the production version, which is not present in mine.

@n1tranquilla It appears that the version on the left is more correct, no? It shows the breakdown of fees. Is that yours?

**Comment by n1tranquilla** [comment]
@robinbb, per block, the current code rolls up to only one internal command per recipient. Is this the correct way? IDK.

**Comment by Isaac-DeFrain** [comment]
Yes, we should aggregate on recipient only (instead of sender & recipient). I think this will require a slight modification to how we represent internal commands.

**Pull request merged**
