### PR TITLE
Reduce dependabot frequency to monthly

### LINKED ISSUE #595: Problem: dependabot PRs too frequent, causing noise

### PR DESCRIPTION
**Pull request by robinbb**
Fixes #595

### CODE REVIEW

**Review by jhult — APPROVED** [review]
LGTM but we can also wait for @trevorbernard if desired.

**Review by trevorbernard — APPROVED** [review]

**Comment by robinbb** [comment]
Happy to have a review from anyone, but it was Trevor who requested the change.

**Comment by robinbb** [comment]
@trevorbernard @jhult I need another review. Sorry to ping you both.

**Review by trevorbernard — APPROVED** [review]
:shipit:

**Pull request merged**
