### PR TITLE
Snark work visibility

### PR DESCRIPTION
**Pull request by Isaac-DeFrain**
- add `SnarkStore` trait
- impl `SnarkStore` for `IndexerStore`
- handle SNARK data on block ingestion
- add client SNARK queries
- handle SNARK queries with `ipc`

Solves https://github.com/Granola-Team/mina-indexer/issues/423

### CODE REVIEW

**Comment by robinbb** [comment]
@Isaac-DeFrain this is a non-draft PR, but I am suspicious that it is not done and cannot be merged because: (1) there is a TODO list in the description, and (2) you have not assigned a reviewer.

**Comment by Isaac-DeFrain** [comment]
I removed the TODO list from the description and assigned you, @robinbb, since Trevor is out today

**Review by robinbb — CHANGES_REQUESTED** [review]
This PR does more than solve the problem that it claims to solve, so it is malformed w.r.t. the rules of this repo (the C4 rules). Also, it removes tests, which is not allowed.

**Comment by Isaac-DeFrain** [comment]
Accidentally closed and re-opened. Should be compatible with C4 now.

**Review by trevorbernard — APPROVED** [review]

**Pull request merged**
