### PR TITLE
Add block parsing performance app

### PR DESCRIPTION
**Pull request by trevorbernard**

### CODE REVIEW

**Review by jenr24G — CHANGES_REQUESTED** [review]
This is good! Do you think it would work as an Integration Test?

**Comment by Isaac-DeFrain** [comment]
Checkout the `test/mainnet-binary` branch. I wrote something very similar. You may want to take some of the benchmarks from there.

**Comment by Isaac-DeFrain** [comment]
Check [this](https://github.com/Granola-Team/mina-indexer/pull/104) before merging

**Comment by trevorbernard** [comment]
I might remove this PR but leave the branch. @Isaac-DeFrain your PR seems more legit

**Pull request closed without merging**
