### PR TITLE
Maintain same API as minaexplorer

### PR DESCRIPTION
**Pull request by trevorbernard**

### CODE REVIEW

**Comment by jhult** [comment]
@trevorbernard, do only certain variables need the `#[graphql(name)` macro?

**Comment by trevorbernard** [comment]
> @trevorbernard, do only certain variables need the `#[graphql(name)` macro?

It's a bug in the mina explorer API. They should all be camelCase but those exist as snake_case so I have to make them an exception

**Review by robinbb — APPROVED** [review]
I note absence of tests in this PR?

**Comment by jhult** [comment]
> > @trevorbernard, do only certain variables need the `#[graphql(name)` macro?
> 
> It's a bug in the mina explorer API. They should all be camelCase but those exist as snake_case so I have to make them an exception

Got it. Thanks for the explanation. For the Mina Explorer GraphQL schema, I believe we are working off [this](https://github.com/Granola-Team/mina-block-explorer/blob/main/graphql/schemas/mina-explorer.graphql).

**Pull request merged**
