### PR TITLE
Add GraphQL staking ledger functionality

### PR DESCRIPTION
**Pull request by trevorbernard**

### CODE REVIEW

**Comment by jenr24G** [comment]
What's going on here? Could you add a description of the changes you made @trevorbernard ?

**Review by jstavh — APPROVED** [review]
LGTM! We used some code from here: https://github.com/Granola-Team/mina-indexer/pull/163

**Review by jenr24G — CHANGES_REQUESTED** [review]
I still do not understand why we cannot use the existing `IndexerStore` database. This will be a breaking change for the Snapshot feature, and I don't think it's ready to merge until any potential regressions have been adressed

**Comment by trevorbernard** [comment]
The reason why I didn’t use the existing DB is because you can’t import staking ledgers when the indexer is running because it already has a reference to all the other column families.

**Review by jenr24G — APPROVED** [review]

**Pull request merged**
