### PR TITLE
(cli) Add ledger memoize flag

### LINKED ISSUE #1381: No way to control ledger best/staged memoization from cli

### PR DESCRIPTION
**Pull request by Isaac-DeFrain**
Depends on #1380 (merge this PR after)

## Describe your changes

Add a `--memoize` flag for cli best/staged ledger commands.

## Link issue(s) fixed

Resolves #1381

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have verified new and existing tests pass locally with my changes.
- [x] I verified whether it was necessary to increment the database version.

### CODE REVIEW

**Comment by Isaac-DeFrain** [comment]
Base don #1380

**Comment by n1tranquilla** [comment]
I don't understand the problem this is solving. I will leave this to someone else to merge.

**Comment by n1tranquilla** [comment]
> Based on https://github.com/Granola-Team/mina-indexer/pull/1380

It appers this PR has a dependency on the linked PR, with one additional commit. Let's put this into draft state until the other is merged.

**Comment by jhult** [comment]
This needs to be rebased on `main` (there is just a small conflict). Then it can be converted from a Draft to Ready.

**Pull request merged**
