### PR TITLE
chore: turn off database compression

### PR DESCRIPTION
**Pull request by jhult**

### CODE REVIEW

**Comment by robinbb** [comment]
You should probably also remove the dependencies from the Cargo.toml by altering the features of the speedb package.

**Review by robinbb — APPROVED** [review]

**Comment by robinbb** [comment]
This is mergeable, at your whim. But regardless of whether it is merged, we should know the effect upon performance and database space (even if only approximately).

**Comment by robinbb** [comment]
Okay, I tested this on a database of 12,345 block height by timing 'just tier3'. Results:

Without it: took 4 min 51 s. DB/snapshot size was 4391 MB.
With this PR: took 6 min 31 s. DB/snapshot size was 20684 MB.

So, the database is 5 times bigger, and it's much slower. So, we should not do this because even if we add compression to the snapshot, everything is slower.

This was run on a machine with a very fast NVMe disk for the data, FYI.

**Comment by jhult** [comment]
@robinbb, thanks for testing. I was trying to do so but ran out of disk space 🤦‍♂️.

**Pull request closed without merging**
