### PR TITLE
Remove proof so serde_json::from_slice(&bytes) works

### PR DESCRIPTION
**Pull request by jhult**
Original: https://github.com/Granola-Team/mina-rs/pull/3

### CODE REVIEW

**Comment by trevorbernard** [comment]
This needs more discussion as the change will likely break something inside mina-rs serialization.

**Comment by trevorbernard** [comment]
The primary reason for this breaking change is to improve the ingestion performance of the Precomputed Blocks. Unfortunately the JSON in the PCB is not valid JSON as it's not valid UTF8 unicode. Most of this non-compliance lies in the various proofs which are unnecessary for our block ingestion.

So as a work around when parsing PCBs we must read all the bytes and call `String::from_utf8_lossy(...)`. As the name implies, it replaces all invalid utf8 characters with the following: https://doc.rust-lang.org/std/char/constant.REPLACEMENT_CHARACTER.html. This is a bandaid to get the PCB to deserialize but is also inefficient as we need to allocate a large string and do a cleaning pass.

With this change we can use the much more efficient `serde_json::from_slice(&bytes)` with slight modification to our internal PCB. This enabled me to ingest 190k blocks in 43mins.

**Comment by robinbb** [comment]
@jhult @trevorbernard What is the plan with this PR?

**Comment by robinbb** [comment]
@jhult I am doing an enormous amount of block ingestion right now, in an effort to ingest the entire chain. If there is a performance increase to be had with this work, then now is the time to invest in it. Is there an easy win, here?

**Comment by trevorbernard** [comment]
Closing this PR and I'll make a proper one with all the fixin's

**Pull request closed without merging**
